/* ==================== MASMORRA - QUESTION BANK ==================== */
/* Predefined ENEM-style questions organized by difficulty and subject */

const MASMORRA_AREAS = {
  linguagens: { name: 'Linguagens e Códigos', icon: '🗣' },
  humanas:    { name: 'Ciências Humanas',     icon: '📜' },
  natureza:   { name: 'Ciências da Natureza',  icon: '🌿' },
  matematica: { name: 'Matemática',            icon: '🔢' }
};

const MASMORRA_DIFFICULTIES = {
  facil: {
    label: 'Fácil',
    description: '15 questões · 60 min',
    timeLimit: 3600,
    icon: '⚔️',
    distribution: { easy: 10, medium: 5, hard: 0 }
  },
  medio: {
    label: 'Médio',
    description: '20 questões · 90 min',
    timeLimit: 5400,
    icon: '🛡️',
    distribution: { easy: 6, medium: 10, hard: 4 }
  },
  dificil: {
    label: 'Difícil',
    description: '30 questões · 120 min',
    timeLimit: 7200,
    icon: '💀',
    distribution: { easy: 5, medium: 10, hard: 15 }
  }
};

const MASMORRA_QUESTIONS = [
  /* ==================== BIOLOGIA ==================== */
  { id: 1, subject: 'biologia', difficulty: 'easy',
    question: 'Qual organela celular é responsável pela produção de energia (ATP)?',
    options: ['Ribossomo', 'Mitocôndria', 'Lisossomo', 'Complexo de Golgi', 'Retículo Endoplasmático'],
    correct: 1, area: 'natureza' },
  { id: 2, subject: 'biologia', difficulty: 'easy',
    question: 'Qual é a função principal dos glóbulos vermelhos no corpo humano?',
    options: ['Combater infecções', 'Transportar oxigênio', 'Coagular o sangue', 'Regular a temperatura', 'Produzir hormônios'],
    correct: 1, area: 'natureza' },
  { id: 3, subject: 'biologia', difficulty: 'easy',
    question: 'O que é fotossíntese?',
    options: ['Processo de respiração celular', 'Processo de produção de energia pelas plantas usando luz solar', 'Processo de decomposição', 'Processo de reprodução assexuada', 'Processo de fermentação'],
    correct: 1, area: 'natureza' },
  { id: 4, subject: 'biologia', difficulty: 'medium',
    question: 'Na cadeia alimentar, os organismos decompositores são fundamentais porque:',
    options: ['Produzem oxigênio para a fotossíntese', 'Reciclam nutrientes e devolvem matéria orgânica ao solo', 'São a base da cadeia trófica', 'Controlam a população de predadores', 'Produzem gás carbônico para as plantas'],
    correct: 1, area: 'natureza' },
  { id: 5, subject: 'biologia', difficulty: 'medium',
    question: 'A seleção natural, proposta por Darwin, pode ser melhor descrita como:',
    options: ['Sobrevivência do mais forte fisicamente', 'Adaptação dos indivíduos mais aptos ao ambiente', 'Mutação dirigida para melhorar a espécie', 'Competição direta entre espécies diferentes', 'Cooperação entre indivíduos da mesma espécie'],
    correct: 1, area: 'natureza' },
  { id: 6, subject: 'biologia', difficulty: 'hard',
    question: 'A resistência bacteriana aos antibióticos é um exemplo de:',
    options: ['Deriva genética', 'Evolução dirigida pela seleção artificial', 'Seleção natural de mutantes resistentes', 'Transgenia natural', 'Simbiose obrigatória'],
    correct: 2, area: 'natureza' },
  { id: 7, subject: 'biologia', difficulty: 'hard',
    question: 'Sobre o ciclo de Krebs, é CORRETO afirmar que:',
    options: ['Ocorre na membrana mitocondrial interna', 'Produz diretamente a maior parte do ATP celular', 'É a etapa final da respiração anaeróbica', 'Oxida o acetil-CoA e libera CO₂ e elétrons para a cadeia transportadora', 'Não requer oxigênio molecular'],
    correct: 3, area: 'natureza' },
  { id: 8, subject: 'biologia', difficulty: 'easy',
    question: 'Qual é a unidade fundamental da vida?',
    options: ['Átomo', 'Molécula', 'Célula', ' tecido', 'Órgão'],
    correct: 2, area: 'natureza' },

  /* ==================== FÍSICA ==================== */
  { id: 10, subject: 'fisica', difficulty: 'easy',
    question: 'Qual é a unidade de medida de força no Sistema Internacional?',
    options: ['Joule', 'Watt', 'Newton', 'Pascal', 'Ampere'],
    correct: 2, area: 'natureza' },
  { id: 11, subject: 'fisica', difficulty: 'easy',
    question: 'Um corpo em queda livre (desconsiderando o atrito do ar) apresenta aceleração:',
    options: ['Variável', 'Nula', 'Constante e igual a g (≈9,8 m/s²)', 'Decrescente com o tempo', 'Depende da massa do corpo'],
    correct: 2, area: 'natureza' },
  { id: 12, subject: 'fisica', difficulty: 'medium',
    question: 'Um automóvel percorre 120 km em 2 horas. Sua velocidade média é:',
    options: ['60 km/h', '120 km/h', '240 km/h', '30 km/h', '480 km/h'],
    correct: 0, area: 'natureza' },
  { id: 13, subject: 'fisica', difficulty: 'medium',
    question: 'A Primeira Lei de Newton (Lei da Inércia) afirma que:',
    options: ['F = m·a', 'Todo corpo continua em repouso ou movimento retilíneo uniforme, a menos que uma força externa atue sobre ele', 'A ação é igual e oposta à reação', 'A energia não se cria nem se destrói', 'O peso é proporcional à massa'],
    correct: 1, area: 'natureza' },
  { id: 14, subject: 'fisica', difficulty: 'hard',
    question: 'Um projectile é lançado horizontalmente do topo de um edifício de 80 m de altura com velocidade de 20 m/s. Desprezando a resistência do ar e considerando g = 10 m/s², qual é o tempo de queda?',
    options: ['2 s', '3 s', '4 s', '8 s', '16 s'],
    correct: 2, area: 'natureza' },
  { id: 15, subject: 'fisica', difficulty: 'hard',
    question: 'Dois corpos de masses m e 2m estão em repouso sobre uma superfície horizontal sem atrito. Uma força F é aplicada em m durante tempo t. Para que 2m atinja a mesma velocidade final, qual seria o tempo necessário aplicando-se a mesma força?',
    options: ['t/2', 't', '2t', '4t', 'Não é possível'],
    correct: 2, area: 'natureza' },

  /* ==================== QUÍMICA ==================== */
  { id: 20, subject: 'quimica', difficulty: 'easy',
    question: 'Qual é o símbolo químico da água?',
    options: ['HO', 'H₂O', 'OH₂', 'H₃O', 'O₂H'],
    correct: 1, area: 'natureza' },
  { id: 21, subject: 'quimica', difficulty: 'easy',
    question: 'Um pH igual a 7 indica uma solução:',
    options: ['Ácida', 'Básica', 'Neutra', 'Superconcentrada', 'Gasosa'],
    correct: 2, area: 'natureza' },
  { id: 22, subject: 'quimica', difficulty: 'medium',
    question: 'Na reação de neutralização entre HCl e NaOH, os produtos formados são:',
    options: ['H₂ + NaClO', 'NaCl + H₂O', 'NaH + ClOH', 'HClO + Na', 'NaO + HCl'],
    correct: 1, area: 'natureza' },
  { id: 23, subject: 'quimica', difficulty: 'medium',
    question: 'O que acontece quando ferro é exposto à umidade e oxigênio por longo período?',
    options: ['Evapora', 'Enferruja (corrosão)', 'Funde', 'Sublima', 'Fissão nuclear'],
    correct: 1, area: 'natureza' },
  { id: 24, subject: 'quimica', difficulty: 'hard',
    question: 'Em uma pilha galvânica de Daniell (Zn/Cu), o que ocorre no eletrodo de zinco?',
    options: ['Redução do Cu²⁺', 'Oxidação do Zn em Zn²⁺', 'Produção de H₂', 'Redução do Zn', 'Nenhuma reação'],
    correct: 1, area: 'natureza' },
  { id: 25, subject: 'quimica', difficulty: 'hard',
    question: 'A constante de equilíbrio Kp para a reação N₂(g) + 3H₂(g) ⇌ 2NH₃(g) a 500 K é 1,5×10⁻⁵ atm⁻². A expressão correta de Kc relacionada é:',
    options: ['Kc = Kp(RT)²', 'Kc = Kp(RT)⁻²', 'Kc = Kp/(RT)²', 'Kc = Kp(RT)⁴', 'Kc = Kp'],
    correct: 3, area: 'natureza' },
  { id: 26, subject: 'quimica', difficulty: 'easy',
    question: 'Qual dos seguintes é um elemento químico?',
    options: ['Água (H₂O)', 'Sal (NaCl)', 'Oxigênio (O₂)', 'Glicose (C₆H₁₂O₆)', 'Amônia (NH₃)'],
    correct: 2, area: 'natureza' },

  /* ==================== HISTÓRIA ==================== */
  { id: 30, subject: 'historia', difficulty: 'easy',
    question: 'Em que ano o Brasil foi descoberto pelos portugueses?',
    options: ['1400', '1492', '1500', '1532', '1600'],
    correct: 2, area: 'humanas' },
  { id: 31, subject: 'historia', difficulty: 'easy',
    question: 'Quem foi o primeiro presidente do Brasil?',
    options: ['Getúlio Vargas', 'Dom Pedro I', 'Deodoro da Fonseca', 'Tiradentes', 'Juscelino Kubitschek'],
    correct: 2, area: 'humanas' },
  { id: 32, subject: 'historia', difficulty: 'medium',
    question: 'A Revolução Industrial teve como principal consequência:',
    options: ['Abolição da escravidão mundial', 'Mecanização da produção e urbanização acelerada', 'Unificação da Alemanha', 'Descoberta da penicilina', 'Criação da ONU'],
    correct: 1, area: 'humanas' },
  { id: 33, subject: 'historia', difficulty: 'medium',
    question: 'A proclamação da independência do Brasil, em 1822, teve como contexto:',
    options: ['Invasão holandesa', 'Ocupação napoleônica de Portugal', 'Guerra dos Farrapos', 'Revolução Francesa', 'Abolição do trabalho escravo'],
    correct: 1, area: 'humanas' },
  { id: 34, subject: 'historia', difficulty: 'hard',
    question: 'O Regime Militar no Brasil (1964-1985) pode ser compreendido no contexto:',
    options: ['Da Guerra Fria e da influência dos EUA na América Latina', 'Da Revolução Russa', 'Da Segunda Guerra Mundial', 'Da descolonização africana', 'Da Revolução Francesa'],
    correct: 0, area: 'humanas' },
  { id: 35, subject: 'historia', difficulty: 'hard',
    question: 'O Estado Novo de Getúlio Vargas (1937-1945) caracterizou-se por:',
    options: ['Extrema democratização da política', 'Industrialização com base no trabalhismo e autoritarismo', 'Aumento da influência inglesa', 'Abertura comercial irrestrita', 'Federalismo radical'],
    correct: 1, area: 'humanas' },

  /* ==================== GEOGRAFIA ==================== */
  { id: 40, subject: 'geografia', difficulty: 'easy',
    question: 'Qual é o maior país do mundo em área territorial?',
    options: ['China', 'Estados Unidos', 'Canadá', 'Rússia', 'Brasil'],
    correct: 3, area: 'humanas' },
  { id: 41, subject: 'geografia', difficulty: 'easy',
    question: 'O Brasil é dividido em quantas regiões geográficas?',
    options: ['3', '4', '5', '6', '8'],
    correct: 2, area: 'humanas' },
  { id: 42, subject: 'geografia', difficulty: 'medium',
    question: 'O desmatamento na Amazônia pode acarretar:',
    options: ['Aumento da biodiversidade', 'Desequilíbrio climático global e perda de espécies', 'Diminuição do nível do mar', 'Aumento da produtividade agrícola', 'Redução do efeito estufa'],
    correct: 1, area: 'humanas' },
  { id: 43, subject: 'geografia', difficulty: 'medium',
    question: 'A globalização econômica trouxe como consequência para os países periféricos:',
    options: ['Redução de todas as desigualdades sociais', 'Maior dependência econômica e vulnerabilidade externa', 'Eliminação do trabalho informal', 'Solução definitiva da fome mundial', 'Aumento da autossuficiência'],
    correct: 1, area: 'humanas' },
  { id: 44, subject: 'geografia', difficulty: 'hard',
    question: 'O conceito de "espacos globalizados" refere-se a:',
    options: ['Regiões rurais isoladas', 'Centros urbanos integrados à economia mundial via fluxos de capital e informação', 'Áreas de preservação ambiental', 'Zonas industriais obsoletas', 'Territórios indígenas'],
    correct: 1, area: 'humanas' },

  /* ==================== FILOSOFIA ==================== */
  { id: 50, subject: 'filosofia', difficulty: 'easy',
    question: 'Sócrates é conhecido por qual método filosófico?',
    options: ['Empirismo', 'Método socrático (diálogo e perguntas)', 'Dialética hegeliana', 'Fenomenologia', 'Estruturalismo'],
    correct: 1, area: 'humanas' },
  { id: 51, subject: 'filosofia', difficulty: 'medium',
    question: 'A frase "Penso, logo existo" é de qual filósofo?',
    options: ['Kant', 'Hume', 'Descartes', 'Nietzsche', 'Platão'],
    correct: 2, area: 'humanas' },
  { id: 52, subject: 'filosofia', difficulty: 'hard',
    question: 'Para Marx, a "alienação" no sistema capitalista se manifesta quando:',
    options: ['O trabalhador se identifica plenamente com seu trabalho', 'O trabalhador se sente parte do produto de seu trabalho', 'O trabalhador se distancia do produto, do processo, de si mesmo e dos outros', 'O trabalhador recebe salário justo', 'O trabalhador participa dos lucros da empresa'],
    correct: 2, area: 'humanas' },

  /* ==================== LINGUAGENS ==================== */
  { id: 60, subject: 'linguagens', difficulty: 'easy',
    question: 'Qual é o sujeito na frase: "Choveu ontem à noite"?',
    options: ['Sujeito simples', 'Sujeito composto', 'Sujeito oculto', 'Sujeito inexistente (frase sem sujeito)', 'Sujeito coletivo'],
    correct: 3, area: 'linguagens' },
  { id: 61, subject: 'linguagens', difficulty: 'easy',
    question: 'Qual palavra está escrita corretamente?',
    options: ['Excessão', 'Exeção', 'Exceção', 'Exssessão', 'Exeçao'],
    correct: 2, area: 'linguagens' },
  { id: 62, subject: 'linguagens', difficulty: 'medium',
    question: 'Na frase "Embora estivesse cansado, continuou trabalhando", o conectivo "embora" estabelece relação de:',
    options: ['Causa', 'Concessão', 'Consequência', 'Finalidade', 'Tempo'],
    correct: 1, area: 'linguagens' },
  { id: 63, subject: 'linguagens', difficulty: 'medium',
    question: 'Um texto dissertativo-argumentativo deve conter obrigatoriamente:',
    options: ['Narração de fatos reais', 'Uma tese defendida com argumentos', 'Diálogos entre personagens', 'Descrição detalhada de cenários', 'Versos e rimas'],
    correct: 1, area: 'linguagens' },
  { id: 64, subject: 'linguagens', difficulty: 'hard',
    question: 'Em Machado de Assis, o narrador em primeira pessoa em "Dom Casmurro" contribui para:',
    options: ['Objetividade absoluta dos fatos', 'Ambiguidade e questionamento sobre a verdade', 'Documentação histórica fidedigna', 'Distanciamento crítico total', 'Comicidade irrestrita'],
    correct: 1, area: 'linguagens' },
  { id: 65, subject: 'linguagens', difficulty: 'hard',
    question: 'A Estilística estuda:',
    options: ['Apenas a morfologia das palavras', 'As escolhas linguísticas do autor e seu efeito estético', 'Apenas a gramática normativa', 'Apenas os erros de português', 'O vocabulário técnico científico'],
    correct: 1, area: 'linguagens' },

  /* ==================== MATEMÁTICA ==================== */
  { id: 70, subject: 'matematica', difficulty: 'easy',
    question: 'Quanto é 15% de 200?',
    options: ['20', '25', '30', '35', '40'],
    correct: 2, area: 'matematica' },
  { id: 71, subject: 'matematica', difficulty: 'easy',
    question: 'Qual é o valor de √144?',
    options: ['11', '12', '13', '14', '144'],
    correct: 1, area: 'matematica' },
  { id: 72, subject: 'matematica', difficulty: 'easy',
    question: 'Se um produto que custava R$ 80,00 teve um aumento de 25%, qual é o novo preço?',
    options: ['R$ 95,00', 'R$ 100,00', 'R$ 105,00', 'R$ 110,00', 'R$ 120,00'],
    correct: 1, area: 'matematica' },
  { id: 73, subject: 'matematica', difficulty: 'medium',
    question: 'Um investimento de R$ 5.000,00 renderá juros simples de 10% ao mês por 6 meses. Qual será o montante final?',
    options: ['R$ 5.500,00', 'R$ 8.000,00', 'R$ 5.300,00', 'R$ 5.800,00', 'R$ 3.000,00'],
    correct: 1, area: 'matematica' },
  { id: 74, subject: 'matematica', difficulty: 'medium',
    question: 'Em uma progressão aritmética (PA), o primeiro termo é 3 e a razão é 5. Qual é o 10º termo?',
    options: ['45', '48', '50', '53', '55'],
    correct: 1, area: 'matematica' },
  { id: 75, subject: 'matematica', difficulty: 'medium',
    question: 'Uma reta é paralela a outra quando:',
    options: ['Se cortam em ângulo reto', 'Não possuem ponto em comum', 'São concorrentes', 'São perpendiculares', 'São coincidentes'],
    correct: 1, area: 'matematica' },
  { id: 76, subject: 'matematica', difficulty: 'hard',
    question: 'Uma função quadrática f(x) = ax² + bx + c tem gráfico com concavidade para baixo e dois zeros reais quando:',
    options: ['a > 0 e Δ < 0', 'a < 0 e Δ > 0', 'a > 0 e Δ > 0', 'a < 0 e Δ = 0', 'a = 0 e Δ > 0'],
    correct: 1, area: 'matematica' },
  { id: 77, subject: 'matematica', difficulty: 'hard',
    question: 'Se cos(α) = 3/5 e α está no 1º quadrante, então sen(α) vale:',
    options: ['3/5', '4/5', '5/3', '5/4', '-4/5'],
    correct: 1, area: 'matematica' },
  { id: 78, subject: 'matematica', difficulty: 'hard',
    question: 'O determinante da matriz A = [[2, 3], [1, 4]] é:',
    options: ['5', '8', '11', '14', '-5'],
    correct: 0, area: 'matematica' },
  { id: 79, subject: 'matematica', difficulty: 'hard',
    question: 'Qual é a solução da inequação 2x - 3 > 5x + 6?',
    options: ['x > -3', 'x < -3', 'x > 3', 'x < 3', 'x = -3'],
    correct: 1, area: 'matematica' },
  { id: 80, subject: 'matematica', difficulty: 'easy',
    question: 'Qual é o resultado de (-3)² ?',
    options: ['9', '-9', '6', '-6', '3'],
    correct: 0, area: 'matematica' },

  /* ==================== MAIS QUESTÕES DIVERSIFICADAS ==================== */
  { id: 90, subject: 'biologia', difficulty: 'medium',
    question: 'O sistema imunológico humano possui células de defesa chamadas linfócitos T, que são responsáveis por:',
    options: ['Produzir anticorpos diretamente', 'Destruir células infectadas e regular a resposta imunológica', 'Transportar oxigênio no sangue', 'Produzir hormônios tireoidianos', 'Formar os ossos do corpo'],
    correct: 1, area: 'natureza' },
  { id: 91, subject: 'biologia', difficulty: 'hard',
    question: 'A clonagem por transferência nuclear (Dolly, 1996) demonstrou que:',
    options: ['Células adultas diferenciadas podem ser reprogramadas', 'A clonagem é impossível em mamíferos', 'O DNA mitocondrial é suficiente para o desenvolvimento', 'Embriões não podem ser manipulados', 'A meiose pode ser suprimida'],
    correct: 0, area: 'natureza' },
  { id: 92, subject: 'fisica', difficulty: 'easy',
    question: 'A velocidade da luz no vácuo é aproximadamente:',
    options: ['300 m/s', '3.000 m/s', '300.000 km/s', '300.000 m/s', '3.000.000 km/s'],
    correct: 2, area: 'natureza' },
  { id: 93, subject: 'fisica', difficulty: 'medium',
    question: 'A energia potencial gravitacional de um corpo de massa 2 kg a 10 m de altura (g = 10 m/s²) é:',
    options: ['20 J', '100 J', '200 J', '400 J', '2.000 J'],
    correct: 2, area: 'natureza' },
  { id: 94, subject: 'quimica', difficulty: 'easy',
    question: 'Qual é o número atômico do carbono?',
    options: ['4', '6', '8', '12', '14'],
    correct: 1, area: 'natureza' },
  { id: 95, subject: 'quimica', difficulty: 'medium',
    question: 'Hidrocarbonetos são compostos formados exclusivamente por:',
    options: ['Carbono e oxigênio', 'Carbono e hidrogênio', 'Carbono e nitrogênio', 'Hidrogênio e oxigênio', 'Carbono, hidrogênio e oxigênio'],
    correct: 1, area: 'natureza' },
  { id: 96, subject: 'quimica', difficulty: 'hard',
    question: 'A reação de esterificação entre um ácido carboxílico e um álcool produz:',
    options: ['Sal + água', 'Éster + água', 'Álcool + ácido', 'Cetona + gás', 'Éter + CO₂'],
    correct: 1, area: 'natureza' },
  { id: 97, subject: 'historia', difficulty: 'easy',
    question: 'Aescravidão no Brasil foi abolida em qual ano?',
    options: ['1850', '1870', '1888', '1900', '1930'],
    correct: 2, area: 'humanas' },
  { id: 98, subject: 'historia', difficulty: 'medium',
    question: 'A Revolução Francesa de 1789 teve como lema:',
    options: ['"Pão e paz"', '"Liberdade, igualdade, fraternidade"', '"O trabalhador do mundo, unite-se"', '"Deus, pátria e família"', '"Um só povo, uma só nação"'],
    correct: 1, area: 'humanas' },
  { id: 99, subject: 'geografia', difficulty: 'easy',
    question: 'Qual é o bioma predominante no norte do Brasil?',
    options: ['Cerrado', 'Caatinga', 'Amazônia', 'Mata Atlântica', 'Pampa'],
    correct: 2, area: 'humanas' },
  { id: 100, subject: 'geografia', difficulty: 'hard',
    question: 'O conceito de "desenvolvimento sustentável" proposto pela ONU em 1987 refere-se a:',
    options: ['Crescimento econômico sem restrições', 'Desenvolvimento que atende às necessidades presentes sem comprometer gerações futuras', 'Industrialização acelerada', 'Exploração máxima dos recursos naturais', 'Abandono total da atividade econômica'],
    correct: 1, area: 'humanas' },
  { id: 101, subject: 'matematica', difficulty: 'medium',
    question: 'Um círculo tem raio de 7 cm. Qual é sua área? (Use π ≈ 3,14)',
    options: ['43,96 cm²', '153,86 cm²', '307,72 cm²', '21,98 cm²', '439,60 cm²'],
    correct: 1, area: 'matematica' },
  { id: 102, subject: 'matematica', difficulty: 'hard',
    question: 'Se f(x) = 2x³ - 3x + 1, qual é f\'(1) (derivada de f em x = 1)?',
    options: ['0', '1', '2', '3', '4'],
    correct: 3, area: 'matematica' },
  { id: 103, subject: 'linguagens', difficulty: 'easy',
    question: 'Qual é a classe gramatical da palavra "rapidamente" na frase: "Ele correu rapidamente"?',
    options: ['Substantivo', 'Adjetivo', 'Advérbio', 'Verbo', 'Preposição'],
    correct: 2, area: 'linguagens' },
  { id: 104, subject: 'linguagens', difficulty: 'medium',
    question: 'A metáfora é uma figura de linguagem que:',
    options: ['Repete sílabas para criar ritmo', 'Faz uma comparação implícita entre dois elementos', 'Indica o contrário do que se quer dizer', 'Exagera uma qualidade', 'Indica aproximação de ideias'],
    correct: 1, area: 'linguagens' },
  { id: 105, subject: 'filosofia', difficulty: 'easy',
    question: 'Qual das opções abaixo é uma questão filosófica?',
    options: ['Qual é a capital da França?', 'O que é a justiça?', 'Quantos planetas existem?', 'Quanto custa um litro de leite?', 'Qual é a fórmula da água?'],
    correct: 1, area: 'humanas' },
  { id: 106, subject: 'filosofia', difficulty: 'medium',
    question: 'Para Kant, o imperativo categórico é:',
    options: ['Uma lei física universal', 'Um princípio moral que deve ser universalizável', 'Uma lei científica', 'Um contrato social', 'Um instinto humano'],
    correct: 1, area: 'humanas' },
  { id: 107, subject: 'filosofia', difficulty: 'hard',
    question: 'O existencialismo de Sartre afirma que:',
    options: ['A existência precede a essência', 'A essência precede a existência', 'O homem é determinado pelo destino', 'A liberdade é ilusória', 'Deus define a natureza humana'],
    correct: 0, area: 'humanas' },
  { id: 108, subject: 'biologia', difficulty: 'easy',
    question: 'A respiração celular ocorre em qual organela?',
    options: ['Núcleo', 'Ribossomo', 'Mitocôndria', 'Lisossomo', 'Vacúolo'],
    correct: 2, area: 'natureza' },
  { id: 109, subject: 'fisica', difficulty: 'hard',
    question: 'Dois corpos de mesma massa estão a alturas 2h e h do solo. A razão entre suas energias potenciais gravitacionais é:',
    options: ['1:1', '2:1', '4:1', '1:2', '√2:1'],
    correct: 1, area: 'natureza' },
  { id: 110, subject: 'matematica', difficulty: 'easy',
    question: 'Se x + 5 = 12, qual é o valor de x?',
    options: ['5', '6', '7', '8', '17'],
    correct: 2, area: 'matematica' },
  { id: 111, subject: 'quimica', difficulty: 'easy',
    question: 'Qual gas é essencial para a respiração humana?',
    options: ['Nitrogênio', 'Gás carbônico', 'Oxigênio', 'Hidrogênio', 'Gás nobre'],
    correct: 2, area: 'natureza' },
  { id: 112, subject: 'historia', difficulty: 'hard',
    question: 'A Guerra Fria (1947-1991) opôs principalmente:',
    options: ['Inglaterra e França', 'EUA e União Soviética', 'Alemanha e Japão', 'Brasil e Argentina', 'China e Índia'],
    correct: 1, area: 'humanas' },
  { id: 113, subject: 'geografia', difficulty: 'medium',
    question: 'A Urbanização acelerada no Brasil no século XX gerou:',
    options: ['Desertificação', 'Megacidades com problemas de infraestrutura', 'Redução da população rural', 'Aumento da produção agropecuária', 'Todos os anteriores'],
    correct: 1, area: 'humanas' },
  { id: 114, subject: 'linguagens', difficulty: 'hard',
    question: 'No conto "O Espelho" de Machado de Assis, o narrador-protagonista:',
    options: ['É confiável e imparcial', 'Apresenta autoengano e contradições internas', 'É um observador externo', 'Conta a história em terceira pessoa', 'É um personagem secundário'],
    correct: 1, area: 'linguagens' },
  { id: 115, subject: 'matematica', difficulty: 'medium',
    question: 'Uma aposta de loteria tem probabilidade de 1 em 10 milhões. Expressa em notação científica:',
    options: ['1 × 10⁻⁶', '1 × 10⁻⁷', '1 × 10⁻⁸', '1 × 10⁷', '10 × 10⁻⁶'],
    correct: 1, area: 'matematica' },
  { id: 116, subject: 'biologia', difficulty: 'medium',
    question: 'Os organismos unicelulares se reproduzem principalmente por:',
    options: ['Meiose', 'Fecundação interna', 'Divisão binária', 'Gametas', 'Brotamento'],
    correct: 2, area: 'natureza' },
  { id: 117, subject: 'fisica', difficulty: 'medium',
    question: 'A 2ª Lei de Newton pode ser expressa pela equação:',
    options: ['E = mc²', 'F = m · a', 'V = IR', 'P = F/A', 'p = m · v'],
    correct: 1, area: 'natureza' },
  { id: 118, subject: 'quimica', difficulty: 'medium',
    question: 'O que é uma solução saturada?',
    options: ['Uma solução com pH neutro', 'Uma solução que não dissolve mais soluto a uma dada temperatura', 'Uma solução muito diluída', 'Uma solução de cor intensa', 'Uma solução gasosa'],
    correct: 1, area: 'natureza' },
  { id: 119, subject: 'linguagens', difficulty: 'medium',
    question: 'Qual a classificação sintática da oração: "Ele estudou para passar no concurso"?',
    options: ['Subordinada substantiva objetiva direta', 'Subordinada adverbial final', 'Coordenada sindética explicativa', 'Subordinada adjetiva restritiva', 'Principal'],
    correct: 1, area: 'linguagens' },
  { id: 120, subject: 'matematica', difficulty: 'easy',
    question: 'Qual é o MMC (Mínimo Múltiplo Comum) de 6 e 8?',
    options: ['12', '14', '24', '48', '36'],
    correct: 2, area: 'matematica' },
  { id: 121, subject: 'historia', difficulty: 'easy',
    question: 'O que foi o Movimento dos Sem-Terra (MST)?',
    options: ['Um partido político', 'Um movimento de luta por reforma agrária', 'Uma religião', 'Uma empresa', 'Um exército'],
    correct: 1, area: 'humanas' },
  { id: 122, subject: 'biologia', difficulty: 'hard',
    question: 'O Dogma Central da Biologia Molecular (DNA → RNA → Proteína) pode apresentar exceções quando:',
    options: ['Ocorre tradução reversa (RNA → DNA) em retrovírus', 'Células fazem fotossíntese', 'Ocorre mitose celular', 'Proteínas se unem em dímeros', 'Ribossomos são destruídos'],
    correct: 0, area: 'natureza' },
  { id: 123, subject: 'geografia', difficulty: 'easy',
    question: 'Qual é o rio mais extenso do mundo?',
    options: ['Rio Nilo', 'Rio Amazonas', 'Rio Mississippi', 'Rio Yangtze', 'Rio São Francisco'],
    correct: 1, area: 'humanas' },
  { id: 124, subject: 'filosofia', difficulty: 'medium',
    question: 'A alegoria da caverna, de Platão, ilustra:',
    options: ['A vida cotidiana dos gregos', 'A diferença entre aparência e realidade, e o papel da educação', 'O sistema político ateniense', 'A guerra do Peloponeso', 'A mitologia grega'],
    correct: 1, area: 'humanas' },
  { id: 125, subject: 'fisica', difficulty: 'easy',
    question: 'O som se propaga melhor:',
    options: ['No vácuo', 'No ar', 'Na água', 'Depende da frequência', 'No espaço'],
    correct: 2, area: 'natureza' },
  { id: 126, subject: 'quimica', difficulty: 'hard',
    question: 'Em uma titulação ácido-base, o ponto de equivalência é caracterizado por:',
    options: ['Mudança brusca de pH e cor do indicador', 'pH sempre igual a 7', 'Formação de gás', 'Precipitação', 'Mudança de temperatura'],
    correct: 0, area: 'natureza' },
  { id: 127, subject: 'matematica', difficulty: 'hard',
    question: 'Em um triângulo retângulo, se catetos medem 5 cm e 12 cm, a hipotenusa mede:',
    options: ['13 cm', '15 cm', '17 cm', '7 cm', '10 cm'],
    correct: 0, area: 'matematica' },
  { id: 128, subject: 'linguagens', difficulty: 'easy',
    question: '"Nós" e "nós" se diferenciam pelo uso:',
    options: ['De artigo definido', 'De acento (pronome vs. substantivo)', 'De gênero', 'De número', 'De pessoa'],
    correct: 1, area: 'linguagens' }
];

/* ==================== MASMORRA ENGINE ==================== */
function getMasmorraQuestions(difficulty) {
  const config = MASMORRA_DIFFICULTIES[difficulty];
  if (!config) return [];

  const pool = { easy: [], medium: [], hard: [] };
  MASMORRA_QUESTIONS.forEach(q => {
    if (pool[q.difficulty]) pool[q.difficulty].push(q);
  });

  const selected = [];
  for (const [level, count] of Object.entries(config.distribution)) {
    const available = shuffleArray([...(pool[level] || [])]);
    selected.push(...available.slice(0, count));
  }

  return shuffleArray(selected).map((q, i) => ({
    ...q,
    _area: q.area || mapSubjectToArea(q.subject),
    _index: i
  }));
}
